# Generated by Django 5.2 on 2026-06-18 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone', models.CharField(max_length=15)),
                ('registro', models.CharField(max_length=10)),
                ('disciplina', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='img/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('matricula', models.CharField(max_length=10)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, upload_to='img/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('X', 'Cancelada'), ('C', 'Confirmada'), ('R', 'Realizada')], default='A', max_length=1)),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.professor')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.aluno')),
            ],
        ),
    ]
